@host = http://localhost:3010
@contentType = application/json

@csrfToken = Cwlrlznm-NRDkURgm4_tvSCtamLmaeXP_IWs

###
GET {{host}}/auth/csrf HTTP/1.1
content-type: {{contentType}}

###
POST {{host}}/auth/login HTTP/1.1
content-type: {{contentType}}
Accept: {{contentType}}
csrf-token: {{csrfToken}}

{
    "email": "user1@test.com",
    "password": "user1"
}

###
# 全てのCPUを取得
GET {{host}}/cpu
Accept: {{contentType}}

###
# IDによる単一のCPUを取得
GET {{host}}/cpu/1
Accept: {{contentType}}
csrf-token: {{csrfToken}}

###
# キーワードによるCPUの検索
GET {{host}}/cpu/search?keyword=Intel
Accept: {{contentType}}
csrf-token: {{csrfToken}}

###
# 新しいCPUを作成
POST {{host}}/cpu
Content-Type: {{contentType}}
Accept: {{contentType}}
csrf-token: {{csrfToken}}

{
  "name": "Intel Core i7",
  "brand": "Intel",
  "processor": "i7",
  "socket": "LGA1151",
  "partNumber": "BX80684I79700K",
  "image": "http://example.com/image.jpg",
  "url": "http://example.com/product",
  "price": "350",
  "categoryId": 1
}

###
# 既存のCPUを更新
PUT {{host}}/cpu/1
Content-Type: {{contentType}}
Accept: {{contentType}}
csrf-token: {{csrfToken}}

{
  "name": "Intel Core i7-9700K",
  "brand": "Intel",
  "processor": "i7",
  "socket": "LGA1151",
  "partNumber": "BX80684I79700KF",
  "image": "http://example.com/image.jpg",
  "url": "http://example.com/product",
  "price": "340",
  "categoryId": 1
}

###
# CPUを削除
DELETE {{host}}/cpu/1
Accept: {{contentType}}
csrf-token: {{csrfToken}}